from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Rule:
    gate_id: str
    label: str
    invariant: str
    failure_mode: str
    trigger_event: str
    trigger_paths: tuple[str, ...]
    check_context: str
    impact: str
    signal_groups: tuple[tuple[str, tuple[str, ...]], ...]
    negative_terms: tuple[str, ...]


RULES = (
    Rule(
        "custom:migration_compatibility",
        "Migration compatibility",
        "Schema changes remain safe for the deployed application and supported rollback window.",
        "A migration can strand an older application version, lose data, or prevent rollback.",
        "pull_request",
        ("**/migrations/**", "**/schema.*", "**/models/**"),
        "custom / migration-compatibility",
        "high",
        (
            ("migration surface", ("/migrations/", "migration", "alembic", "prisma/schema")),
            (
                "persistent data",
                ("database", "postgres", "sqlite", "duckdb", "sqlalchemy", "coredata"),
            ),
            ("deployment lifecycle", ("deploy", "rollback", "production", "release")),
        ),
        ("migration", "rollback", "backward", "downgrade"),
    ),
    Rule(
        "custom:api_compatibility",
        "API compatibility",
        "Public request, response, and event contracts remain compatible or intentionally versioned.",
        "A consumer can break even when the provider's unit tests still pass.",
        "pull_request",
        ("**/*.proto", "**/openapi*", "**/*.graphql", "**/api/**"),
        "custom / api-compatibility",
        "high",
        (
            ("machine-readable contract", ("openapi", ".proto", ".graphql", "json schema")),
            ("consumer boundary", ("/api/", "/client", "/sdk", "public api", "webhook")),
            (
                "compatibility policy",
                ("backward compat", "breaking change", "versioning", "deprecat"),
            ),
        ),
        ("compat", "breaking", "version", "consumer"),
    ),
    Rule(
        "custom:generated_artifact_drift",
        "Generated artifact drift",
        "Committed generated artifacts match their checked-in source definitions.",
        "Generated clients, bindings, snapshots, or schemas can silently diverge from source.",
        "pull_request",
        ("**/generated/**", "**/*.proto", "**/schema/**"),
        "custom / generated-artifacts-current",
        "medium",
        (
            ("generation command", ("generate", "codegen", "gen:", "build.rs", "swiftgen")),
            ("generated output", ("/generated/", ".generated.", "do not edit", "autogenerated")),
        ),
        ("generated", "drift", "up to date", "dirty"),
    ),
    Rule(
        "custom:package_integrity",
        "Package integrity",
        "The distributable application preserves signing, entitlements, bundled resources, and launchability.",
        "Source checks can pass while the packaged application is unsigned, incomplete, or unable to launch.",
        "release",
        ("**/*.entitlements", "**/*.xcodeproj/**", "**/tauri.conf.json", "**/electron-builder.*"),
        "custom / package-integrity",
        "high",
        (
            ("application package", (".xcodeproj", "tauri.conf", "electron-builder", "info.plist")),
            ("distribution boundary", ("entitlements", "codesign", "notar", "package", "bundle")),
            ("launch verification", ("launch", "smoke", "install", "artifact")),
        ),
        ("package", "launch", "codesign", "entitlement"),
    ),
    Rule(
        "custom:adapter_parity",
        "Adapter parity",
        "Every supported adapter preserves the shared behavior and safety contract.",
        "One provider or adapter can drift while tests cover only the default implementation.",
        "pull_request",
        ("**/adapters/**", "**/providers/**", "**/connectors/**"),
        "custom / adapter-parity",
        "high",
        (
            (
                "multiple implementations",
                ("/adapters/", "/providers/", "/connectors/", "provider_"),
            ),
            ("shared contract", ("protocol", "interface", "abstract", "trait", "adapter contract")),
            ("selection or routing", ("router", "registry", "dispatch", "provider selection")),
        ),
        ("adapter", "provider", "parity", "contract"),
    ),
    Rule(
        "custom:machine_contract",
        "Machine-facing contract",
        "CLI and API surfaces preserve schemas, exit behavior, and documented automation semantics.",
        "A command can remain human-usable while breaking agents or integrations that depend on structure.",
        "pull_request",
        ("**/cli*", "**/api/**", "**/schemas/**", ".agents/**"),
        "custom / machine-contract",
        "high",
        (
            ("machine surface", ("cli", "argparse", "clap", "commander", "/api/", "mcp")),
            ("structured contract", ("schema", "--json", "exit code", "machine-readable")),
            ("agent or integration docs", (".agents/", "skill.md", "integration", "automation")),
        ),
        ("schema", "exit", "json", "contract"),
    ),
    Rule(
        "custom:restore_drill",
        "Restore drill",
        "Backups can be restored into a usable state with integrity checks.",
        "A backup can exist but be incomplete, stale, corrupt, or operationally unrestorable.",
        "scheduled",
        ("**/backup/**", "**/restore/**", "**/migrations/**"),
        "custom / restore-drill",
        "medium",
        (
            ("persistent data", ("database", "sqlite", "postgres", "duckdb", "coredata")),
            ("backup or restore path", ("backup", "restore", "snapshot", "recovery")),
            ("integrity procedure", ("integrity", "verify", "checksum", "drill", "recovery test")),
        ),
        ("restore", "corrupt", "integrity", "recovery"),
    ),
    Rule(
        "custom:accessibility_automation_contract",
        "Accessibility and automation contract",
        "Interactive controls expose stable roles, labels, identifiers, and state for accessibility and automation.",
        "The app can look correct while remaining ambiguous or unreachable to assistive and Mac automation tools.",
        "pull_request",
        ("**/*.swift", "**/*.xib", "**/*.storyboard", "**/src-tauri/**"),
        "custom / accessibility-automation-contract",
        "high",
        (
            (
                "visible application",
                ("swiftui", "appkit", "nsapplication", "tauri.conf", "electron"),
            ),
            (
                "accessibility semantics",
                ("accessibilityidentifier", "accessibilitylabel", "aria-label", "axuielement"),
            ),
            ("interactive surface", ("button", "menu", "toolbar", "shortcut", "command")),
        ),
        ("accessibility", "identifier", "label", "automation"),
    ),
)
