"""Read-only repository hygiene checks and conservative ignore updates."""

from __future__ import annotations

import fnmatch
import json
import subprocess
import time
import tomllib
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any

from .repo_hygiene_package import _package_manager_state

REPO_HYGIENE_SCHEMA = "repo-hygiene-v1"
RECENT_COMMIT_SECONDS = 24 * 60 * 60

_GENERATED_MARKER_DIRECTORY_NAMES = frozenset({"autogen", "autogenerated", "generated", "gen"})


@dataclass(frozen=True)
class GeneratedRule:
    rule: str
    code: str
    evidence: str


def check_repo_hygiene(repo_path: Path) -> dict[str, Any]:
    """Return a deterministic, non-mutating repository hygiene report."""

    input_path = repo_path.expanduser().resolve()
    repo_root = _git_root(input_path)
    tracked_paths = _git_paths(repo_root, "ls-files", "-z", "--")
    languages = _detect_languages(repo_root, tracked_paths)
    config = _repo_hygiene_config(repo_root)
    path_exceptions = _string_list(config.get("generated_path_exceptions"))
    generated_paths: list[dict[str, Any]] = []
    missing_by_rule: dict[str, dict[str, Any]] = {}
    exceptions: list[dict[str, Any]] = []

    for relative in tracked_paths:
        rule = _generated_rule(repo_root, relative, languages)
        if rule is None:
            if _ambiguous_directory(relative):
                exceptions.append(
                    {
                        "code": "ambiguous-directory-preserved",
                        "path": relative,
                        "reason": "build/ and data/ are not disposable without stronger evidence",
                    }
                )
            continue
        if _matches_any(relative, path_exceptions):
            exceptions.append(
                {
                    "code": "configured-generated-path-exception",
                    "path": relative,
                    "reason": "repository explicitly preserves this generated-looking path",
                }
            )
            continue
        ignored = _is_ignored(repo_root, relative)
        item = {
            "path": relative,
            "rule": rule.rule,
            "evidence": rule.evidence,
            "ignore_covered": ignored,
            "status": "tracked-generated-output",
        }
        generated_paths.append(item)
        if not ignored:
            missing = missing_by_rule.setdefault(
                rule.rule,
                {
                    "rule": rule.rule,
                    "code": rule.code,
                    "paths": [],
                    "reason": "confirmed generated output is not covered by Git ignore rules",
                },
            )
            paths = missing["paths"]
            if isinstance(paths, list):
                paths.append(relative)

    package_manager = _package_manager_state(repo_root, tracked_paths, languages, config)
    violations: list[dict[str, Any]] = [
        {
            "code": "tracked-generated-output",
            "path": item["path"],
            "severity": "error",
            "message": "Generated output is tracked by Git; ignore coverage alone does not untrack it.",
            "evidence": item["evidence"],
            "ignore_covered": item["ignore_covered"],
        }
        for item in generated_paths
    ]
    for missing in missing_by_rule.values():
        violations.append(
            {
                "code": "generated-ignore-rule-missing",
                "path": missing["rule"],
                "severity": "error",
                "message": missing["reason"],
                "paths": sorted(missing["paths"]),
            }
        )
    violations.extend(package_manager["violations"])
    workspace = package_manager["workspace"]
    if workspace["missing_workspace_file"]:
        violations.append(
            {
                "code": "pnpm-workspace-file-missing",
                "path": "pnpm-workspace.yaml",
                "severity": "warning",
                "message": "Multiple product packages were found without a workspace declaration.",
                "package_paths": workspace["package_paths"],
            }
        )

    ci = _ci_state(repo_root)
    ownership = _ownership_state(repo_root)
    configured_exceptions = _configured_exceptions(config)
    exceptions.extend(configured_exceptions)
    status = "pass" if not violations else "fail"
    return {
        "schema": REPO_HYGIENE_SCHEMA,
        "status": status,
        "repo_root": str(repo_root),
        "input_path": str(input_path),
        "languages": sorted(languages),
        "generated_paths": generated_paths,
        "violations": violations,
        "missing_ignore_rules": sorted(
            missing_by_rule.values(), key=lambda item: str(item["rule"])
        ),
        "exceptions": _deduplicate_exceptions(exceptions),
        "package_manager": package_manager,
        "workspace": workspace,
        "ci": ci,
        "ownership": ownership,
        "blocked_ownership_state": ownership if ownership["status"] == "blocked" else None,
        "implementation_allowed": False,
    }


def apply_confirmed_ignore_rules(repo_path: Path, *, apply: bool) -> dict[str, Any]:
    """Preview or append only rules confirmed by :func:`check_repo_hygiene`."""

    report = check_repo_hygiene(repo_path)
    rules = [str(item["rule"]) for item in report["missing_ignore_rules"]]
    result: dict[str, Any] = {
        **report,
        "operation": "apply-confirmed-ignore-rules",
        "apply": apply,
        "would_add_ignore_rules": rules,
        "added_ignore_rules": [],
    }
    if not apply:
        result["status"] = "preview"
        return result
    ownership = report["ownership"]
    if not isinstance(ownership, dict) or ownership.get("status") != "clear":
        result["status"] = "blocked"
        result["implementation_allowed"] = False
        return result
    if not rules:
        result["status"] = "no-op"
        result["implementation_allowed"] = True
        return result

    gitignore = Path(str(report["repo_root"])) / ".gitignore"
    original = gitignore.read_text(encoding="utf-8") if gitignore.exists() else ""
    existing_lines = {line.strip() for line in original.splitlines() if line.strip()}
    additions = [rule for rule in rules if rule not in existing_lines]
    if additions:
        content = original
        if content and not content.endswith("\n"):
            content += "\n"
        if content and not content.endswith("\n\n"):
            content += "\n"
        content += "# Quality Runner confirmed generated outputs\n"
        content += "".join(f"{rule}\n" for rule in additions)
        gitignore.write_text(content, encoding="utf-8")
    result["status"] = "applied" if additions else "no-op"
    result["added_ignore_rules"] = additions
    result["implementation_allowed"] = True
    return result


def _git_root(path: Path) -> Path:
    result = _git_command(path, "rev-parse", "--show-toplevel")
    if result is None:
        raise ValueError(f"not a Git repository: {path}")
    root = Path(result).expanduser().resolve()
    if not root.is_dir():
        raise ValueError(f"Git root is not a directory: {root}")
    return root


def _git_paths(root: Path, *args: str) -> list[str]:
    output = _git_command(root, *args)
    if output is None:
        raise ValueError(f"Git command failed in repository: {root}")
    return [item for item in output.split("\0") if item]


def _git_command(root: Path, *args: str) -> str | None:
    try:
        result = subprocess.run(
            ["git", *args], cwd=root, capture_output=True, check=False, text=True, timeout=10
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if result.returncode != 0:
        return None
    return result.stdout.rstrip("\n")


def _is_ignored(root: Path, relative: str) -> bool:
    try:
        result = subprocess.run(
            ["git", "check-ignore", "--no-index", "--quiet", "--", relative],
            cwd=root,
            capture_output=True,
            check=False,
            text=True,
            timeout=10,
        )
    except (OSError, subprocess.TimeoutExpired):
        return False
    return result.returncode == 0


def _detect_languages(root: Path, tracked_paths: list[str]) -> set[str]:
    languages: set[str] = set()
    if (root / "package.json").exists():
        languages.update({"javascript", "typescript"})
    if any(
        path in {"pyproject.toml", "setup.py", "setup.cfg", "requirements.txt"}
        or path.endswith("/pyproject.toml")
        for path in tracked_paths
    ):
        languages.add("python")
    if any(
        path == "Package.swift"
        or path.endswith("/Package.swift")
        or ".xcodeproj/" in path
        or ".xcworkspace/" in path
        or path.endswith(".swift")
        for path in tracked_paths
    ):
        languages.add("swift")
    return languages


def _generated_rule(root: Path, relative: str, languages: set[str]) -> GeneratedRule | None:
    parts = tuple(part.lower() for part in PurePosixPath(relative).parts)
    filename = parts[-1] if parts else ""
    if "node_modules" in parts:
        return GeneratedRule(
            "node_modules/", "javascript-dependency-output", "node_modules directory"
        )
    if ".pnpm-store" in parts:
        return GeneratedRule(".pnpm-store/", "javascript-dependency-output", "pnpm store directory")
    if ".quality-runner" in parts:
        return GeneratedRule(
            ".quality-runner/", "quality-runner-artifact", "Quality Runner run artifacts"
        )
    if any(
        parts[index : index + 2] == ("data", "audit-worktrees")
        for index in range(max(0, len(parts) - 1))
    ):
        return GeneratedRule(
            "data/audit-worktrees/",
            "audit-verification-worktree",
            "temporary audit verification worktree",
        )
    directory_rules = {
        ".next": (".next/", "javascript-build-output", "Next.js build output"),
        ".turbo": (".turbo/", "javascript-build-output", "Turborepo cache output"),
        ".parcel-cache": (".parcel-cache/", "javascript-build-output", "Parcel cache output"),
        ".pytest_cache": (".pytest_cache/", "python-test-output", "pytest cache output"),
        ".mypy_cache": (".mypy_cache/", "python-tool-output", "mypy cache output"),
        ".ruff_cache": (".ruff_cache/", "python-tool-output", "Ruff cache output"),
        ".tox": (".tox/", "python-tool-output", "tox environment output"),
        ".nox": (".nox/", "python-tool-output", "nox environment output"),
        ".venv": (".venv/", "python-environment-output", "local Python environment"),
        ".build": (".build/", "swift-build-output", "SwiftPM build output"),
        "deriveddata": ("DerivedData/", "swift-build-output", "Xcode build output"),
        "coverage": ("coverage/", "test-coverage-output", "test coverage output"),
        "dist": ("dist/", "distribution-output", "distribution build output"),
        "storybook-static": (
            "storybook-static/",
            "javascript-build-output",
            "Storybook build output",
        ),
    }
    for part in parts:
        if part in directory_rules:
            rule, code, evidence = directory_rules[part]
            return GeneratedRule(rule, code, evidence)
    if any(part.endswith(".egg-info") for part in parts):
        return GeneratedRule(
            "*.egg-info/", "python-package-output", "Python package metadata output"
        )
    if filename in {".ds_store", ".eslintcache"}:
        return GeneratedRule(filename, "tool-output", "local tool output")
    if filename.endswith(".pyc") or filename.endswith(".pyo"):
        return GeneratedRule("*.py[co]", "python-bytecode-output", "Python bytecode output")
    if filename.endswith(".tsbuildinfo"):
        return GeneratedRule(
            "*.tsbuildinfo", "typescript-build-output", "TypeScript incremental build output"
        )
    if any(part in _GENERATED_MARKER_DIRECTORY_NAMES for part in parts[:-1]):
        marker = _generated_marker(root / relative)
        if marker:
            index = next(
                index
                for index, part in enumerate(parts[:-1])
                if part in _GENERATED_MARKER_DIRECTORY_NAMES
            )
            rule = "/".join(PurePosixPath(relative).parts[: index + 1]) + "/"
            return GeneratedRule(rule, "generated-source-output", marker)
    return None


def _generated_marker(path: Path) -> str | None:
    try:
        content = path.read_text(encoding="utf-8", errors="replace")[:8_192].lower()
    except OSError:
        return None
    for marker in (
        "code generated",
        "do not edit",
        "@generated",
        "autogenerated",
        "generated file",
    ):
        if marker in content:
            return f"generated marker: {marker}"
    return None


def _ambiguous_directory(relative: str) -> bool:
    parts = {part.lower() for part in PurePosixPath(relative).parts}
    return bool(parts & {"build", "data"})


def _ci_state(root: Path) -> dict[str, Any]:
    workflow_root = root / ".github" / "workflows"
    if not workflow_root.is_dir():
        return {"present": False, "workflows": [], "repo_hygiene_gate": "central-sweep"}
    workflows = sorted(
        path.relative_to(root).as_posix()
        for path in workflow_root.iterdir()
        if path.is_file() and path.suffix in {".yml", ".yaml"}
    )
    gate = False
    for relative in workflows:
        try:
            if "repo-hygiene" in relative or "repo-hygiene check" in (root / relative).read_text(
                encoding="utf-8", errors="replace"
            ):
                gate = True
                break
        except OSError:
            continue
    return {
        "present": True,
        "workflows": workflows,
        "repo_hygiene_gate": "configured" if gate else "missing",
    }


def _ownership_state(root: Path) -> dict[str, Any]:
    status = _git_command(root, "status", "--porcelain", "--untracked-files=all") or ""
    worktree_output = _git_command(root, "worktree", "list", "--porcelain") or ""
    worktrees = [
        line.removeprefix("worktree ")
        for line in worktree_output.splitlines()
        if line.startswith("worktree ")
    ]
    reasons: list[str] = []
    if status.strip():
        reasons.append("dirty worktree requires ownership clearance before mutation")
    if len(worktrees) > 1:
        reasons.append("multiple worktrees are present")
    commit_time_text = _git_command(root, "log", "-1", "--format=%ct")
    recent = False
    if commit_time_text and commit_time_text.isdigit():
        recent = time.time() - int(commit_time_text) < RECENT_COMMIT_SECONDS
        if recent:
            reasons.append("HEAD changed within the recent-activity window")
    return {
        "status": "blocked" if reasons else "clear",
        "mutation_allowed": not reasons,
        "reasons": reasons,
        "dirty": bool(status.strip()),
        "worktree_count": len(worktrees),
        "recent_commit": recent,
        "branch": _git_command(root, "branch", "--show-current") or "detached",
    }


def _repo_hygiene_config(root: Path) -> dict[str, Any]:
    path = root / ".quality-runner.toml"
    if not path.exists():
        return {}
    try:
        document = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError):
        return {}
    quality_runner = document.get("quality_runner")
    if not isinstance(quality_runner, dict):
        return {}
    section = quality_runner.get("repo_hygiene")
    return section if isinstance(section, dict) else {}


def _configured_exceptions(config: dict[str, Any]) -> list[dict[str, Any]]:
    reason = config.get("pnpm_version_exception")
    if not isinstance(reason, str) or not reason.strip():
        return []
    return [
        {
            "code": "pnpm-version-exception",
            "reason": reason.strip(),
            "source": ".quality-runner.toml",
        }
    ]


def _string_list(value: object) -> list[str]:
    return (
        [item for item in value if isinstance(item, str) and item]
        if isinstance(value, list)
        else []
    )


def _matches_any(path: str, patterns: list[str]) -> bool:
    return any(path == pattern or fnmatch.fnmatch(path, pattern) for pattern in patterns)


def _deduplicate_exceptions(items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    seen: set[str] = set()
    result: list[dict[str, Any]] = []
    for item in items:
        key = json.dumps(item, sort_keys=True)
        if key not in seen:
            result.append(item)
            seen.add(key)
    return result
